Update build_ut.yml

diff --git a/.github/workflows/build_ut.yml b/.github/workflows/build_ut.yml
--- a/.github/workflows/build_ut.yml
+++ b/.github/workflows/build_ut.yml
@@ -22,10 +22,10 @@ name: build_ut
 # Controls when the workflow will run
 on:
   # Triggers the workflow on push or pull request events but only for the "master" and "release/*" branches
-  push:
-    branches: ["master", "release/*"]
-  pull_request:
-    branches: ["master", "release/*"]
+  # push:
+  #   branches: ["master", "release/*"]
+  # pull_request:
+  #   branches: ["master", "release/*"]
 
   # Allows you to run this workflow manually from the Actions tab
   workflow_dispatch:
@@ -115,74 +115,74 @@ jobs:
             build/*gtest_result.xml
 
       # Upload coverage report on success
-      - name: Upload Coverage Report
-        uses: actions/upload-artifact@v4
-        if: success()
-        with:
-          name: coverage_report
-          path: build/gh_pages/coverage_report
+      # - name: Upload Coverage Report
+      #   uses: actions/upload-artifact@v4
+      #   if: success()
+      #   with:
+      #     name: coverage_report
+      #     path: build/gh_pages/coverage_report
 
-      # Upload coverage statistics on success
-      - name: Upload Coverage Statistics
-        uses: actions/upload-artifact@v4
-        if: success()
-        with:
-          name: coverage_report_stats
-          path: build/coverage_statistics.txt
+      # # Upload coverage statistics on success
+      # - name: Upload Coverage Statistics
+      #   uses: actions/upload-artifact@v4
+      #   if: success()
+      #   with:
+      #     name: coverage_report_stats
+      #     path: build/coverage_statistics.txt
 
-  checks-the-cov-report:
-    name: Checks the Coverage Report
+  # checks-the-cov-report:
+  #   name: Checks the Coverage Report
 
-    # Runs on ubuntu
-    runs-on: ubuntu-24.04
+  #   # Runs on ubuntu
+  #   runs-on: ubuntu-24.04
 
-    # Timeout after
-    timeout-minutes: 2
+  #   # Timeout after
+  #   timeout-minutes: 2
 
-    # # Define the dependencies on the previous coverage jobs
-    needs: [build-test]
+  #   # # Define the dependencies on the previous coverage jobs
+  #   needs: [build-test]
     
-    steps:
-      - name: Checkout repo
-        uses: actions/checkout@v4
+  #   steps:
+  #     - name: Checkout repo
+  #       uses: actions/checkout@v4
     
-      # Download the current coverage statistics
-      - name: Download Current Coverage Statistics
-        uses: actions/download-artifact@v4
-        with:
-          name: coverage_report_stats
-          path: build
+  #     # Download the current coverage statistics
+  #     - name: Download Current Coverage Statistics
+  #       uses: actions/download-artifact@v4
+  #       with:
+  #         name: coverage_report_stats
+  #         path: build
         
-      # Download current master coverage statistics
-      - name: Download Master Coverage Statistics
-        uses: dawidd6/action-download-artifact@v6
-        if: ${{ success() && github.event_name == 'pull_request' && github.base_ref == 'master' }}
-        with:
-          workflow_conclusion: success
-          branch: master
-          name: coverage_report_stats
-          path: master_artifacts
+  #     # Download current master coverage statistics
+  #     - name: Download Master Coverage Statistics
+  #       uses: dawidd6/action-download-artifact@v6
+  #       if: ${{ success() && github.event_name == 'pull_request' && github.base_ref == 'master' }}
+  #       with:
+  #         workflow_conclusion: success
+  #         branch: master
+  #         name: coverage_report_stats
+  #         path: master_artifacts
       
-      # Run the process_coverage_stats script
-      - name: Process Coverage Statistics
-        if: ${{ success() && github.event_name == 'pull_request' && github.base_ref == 'master' }}
-        run: python scripts/coverage/process_coverage_stats.py ./master_artifacts/coverage_statistics.txt build/coverage_statistics.txt
+  #     # Run the process_coverage_stats script
+  #     - name: Process Coverage Statistics
+  #       if: ${{ success() && github.event_name == 'pull_request' && github.base_ref == 'master' }}
+  #       run: python scripts/coverage/process_coverage_stats.py ./master_artifacts/coverage_statistics.txt build/coverage_statistics.txt
       
-      # Get process_coverage_stats script output
-      - id: get-comment-body
-        if: ${{ (success() || failure()) && github.ref != 'refs/heads/master' }}
-        run: |
-          body="$(cat comparison_output.txt)"
-          body="${body//'%'/'%25'}"
-          body="${body//$'\n'/'%0A'}"
-          body="${body//$'\r'/'%0D'}"
-          echo "::set-output name=body::$body"
+  #     # Get process_coverage_stats script output
+  #     - id: get-comment-body
+  #       if: ${{ (success() || failure()) && github.ref != 'refs/heads/master' }}
+  #       run: |
+  #         body="$(cat comparison_output.txt)"
+  #         body="${body//'%'/'%25'}"
+  #         body="${body//$'\n'/'%0A'}"
+  #         body="${body//$'\r'/'%0D'}"
+  #         echo "::set-output name=body::$body"
       
-      # Create comment with coverage info
-      - name: Create Coverage Comment
-        if: ${{ (success() || failure()) && github.ref != 'refs/heads/master' }}
-        uses: peter-evans/create-or-update-comment@v4
-        with:
-          issue-number: ${{ github.event.pull_request.number }}
-          body: ${{ steps.get-comment-body.outputs.body }}
+  #     # Create comment with coverage info
+  #     - name: Create Coverage Comment
+  #       if: ${{ (success() || failure()) && github.ref != 'refs/heads/master' }}
+  #       uses: peter-evans/create-or-update-comment@v4
+  #       with:
+  #         issue-number: ${{ github.event.pull_request.number }}
+  #         body: ${{ steps.get-comment-body.outputs.body }}
   
